### ISSUE TITLE
Segmentation fault with Rails 3.2.9 and Ruby 1.9.3-p286

### ISSUE THREAD

**Issue by coderberry** [banister/plymouth#11]
If I perform a simple spec test where `1.should eq(2)` it gives the following shell response:

http://d.pr/f/XGJL

The gem is completely unusable for me :(

**Comment by banister** [comment]
Try `pry-rescue` instead: https://github.com/conradirwin/pry-rescue

scroll down to 'testing' section and you'll see it mentions rspec.

**Comment by coderberry** [comment]
Worked like a charm. Thanks!
