### ISSUE TITLE
USE_PLYMOUTH=1 environment to control plymouth activation

### ISSUE THREAD

**Issue by erikh** [banister/plymouth#5]
It'd be nice to have something like this for non-interactive runs so they just get the "normal" system and I can still get plymouth without having to modify numerous test files each time I want to use plymouth.

**Comment by banister** [comment]
so this means it's off by default, and users have to explicitly turn it on to use it?

**Comment by banister** [comment]
Is this reasonable? https://github.com/banister/plymouth/commit/bbca2109430d43e03b49a1183b37cdf538596698

I defaulted to plymouth being active by default, and users have to explicitly disable it using USE_PLYMOUTH=0 (or false or no)

**Comment by erikh** [comment]
I think that will still cause problems with CI systems because it's on by default.

**Comment by banister** [comment]
I think that if it's off by default, it creates a potentially annoying barrier to entry as people have to then explicitly `export USE_PLYMOUTH=1` before it starts working, any other solutions?

btw have you used it much? im getting approximately 0 feedback from people so i have no idea if it's working or segfaulting, or just behaving weird :)

**Comment by erikh** [comment]
No ideas -- maybe a text file they can put in .gitignore?

Not yet -- I'll give it a shot when I work on projects this weekend.

**Comment by banister** [comment]
ah good point about travis and friends, i hadnt thought of that hmmm

**Comment by banister** [comment]
what about if they turn it off/on in their projects local `.pryrc` ? `Plymouth.disable!`

**Comment by erikh** [comment]
works for me

**Comment by banister** [comment]
@erikh actually i just spoke to a dude and he said, regarding the travis issue, you could simply set `env: RUN_PLYMOUTH="no"` inside `.travis.yml` is this enough?

**Comment by erikh** [comment]
Sounds awesome.
